### ISSUE TITLE
Rule for failed attempts to form government?

### ISSUE THREAD

**Issue by wbruntra** [trentpiercy/secret-hitler#2]
Love the clean design of this app. I don't see any implementation of the rule where the top policy is automatically enacted after three failed votes for President and Chancellor. I submitted a PR with the logic for that situation:

https://github.com/trentpiercy/secret-hitler/pull/1

Obviously this is a case that doesn't occur often when playing the game, but it still seems worth including. I get that I'm coming out of nowhere with this PR. Sorry about that. Feel free to consider this as just a suggestion.

**Comment by trentpiercy** [comment]
Lol sorry I missed this. Just a little late. 

Thanks so much for the pr! Totally a feature I missed and a welcome addition. Merged! Added just a small styling tweak you can check out.
